//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingsModelWPFDemo.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SettingsModelWPFDemo.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string STR_ABOUT_Copyright {
            get {
                return ResourceManager.GetString("STR_ABOUT_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string STR_ABOUT_Link {
            get {
                return ResourceManager.GetString("STR_ABOUT_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string STR_ABOUT_Modules {
            get {
                return ResourceManager.GetString("STR_ABOUT_Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string STR_About_SETTINGS_Caption {
            get {
                return ResourceManager.GetString("STR_About_SETTINGS_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string STR_ABOUT_Version {
            get {
                return ResourceManager.GetString("STR_ABOUT_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string STR_ACCENT_LABEL {
            get {
                return ResourceManager.GetString("STR_ACCENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a color for highlighting items with your preferred color..
        /// </summary>
        public static string STR_ACCENT_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_ACCENT_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUI Framework Demo Application for SettingsModel.
        /// </summary>
        public static string STR_APP_TITLE {
            get {
                return ResourceManager.GetString("STR_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string STR_Appearance_SETTINGS_Caption {
            get {
                return ResourceManager.GetString("STR_Appearance_SETTINGS_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string STR_APPEARANCE_THEME {
            get {
                return ResourceManager.GetString("STR_APPEARANCE_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string STR_BOOKMARKS_OPTION_CAPTION {
            get {
                return ResourceManager.GetString("STR_BOOKMARKS_OPTION_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build a set of frequently used folders and access them via shortcut in the application.
        /// </summary>
        public static string STR_BOOKMARKS_OPTION_CAPTION_TT {
            get {
                return ResourceManager.GetString("STR_BOOKMARKS_OPTION_CAPTION_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your frequently used paths for usage in this applaiction..
        /// </summary>
        public static string STR_CURRENT_APP_BOOKMARK_CAPTION_TT {
            get {
                return ResourceManager.GetString("STR_CURRENT_APP_BOOKMARK_CAPTION_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Language.
        /// </summary>
        public static string STR_CURRENT_APP_LANG_CAPTION {
            get {
                return ResourceManager.GetString("STR_CURRENT_APP_LANG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your prefered application language.
        /// </summary>
        public static string STR_CURRENT_APP_LANG_CAPTION_TT {
            get {
                return ResourceManager.GetString("STR_CURRENT_APP_LANG_CAPTION_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string STR_DARK_THEME {
            get {
                return ResourceManager.GetString("STR_DARK_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo application implements a Modern UI style in WPF. It demonstrates the SettingsModel project that implements storage and retrieval of program settings via settings folder:.
        /// </summary>
        public static string STR_DEMO_FEATURE1 {
            get {
                return ResourceManager.GetString("STR_DEMO_FEATURE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing a setting (and restarting the application) should result in a changed program behavior (except for Bookmarks and Size of Fixed Font since these only demostrate storage and retrieval of settings)..
        /// </summary>
        public static string STR_DEMO_FEATURE2 {
            get {
                return ResourceManager.GetString("STR_DEMO_FEATURE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Settings and change something to see SettingsModel in action..
        /// </summary>
        public static string STR_DEMO_FEATURE3 {
            get {
                return ResourceManager.GetString("STR_DEMO_FEATURE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a Breakpoint for example at the Engine.AddOption(...) method to see the action..
        /// </summary>
        public static string STR_DEMO_FEATURE4 {
            get {
                return ResourceManager.GetString("STR_DEMO_FEATURE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Font Size.
        /// </summary>
        public static string STR_FIXED_FONT_SIZE_LABEL {
            get {
                return ResourceManager.GetString("STR_FIXED_FONT_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your preferred fixed font size to match your screen resolution..
        /// </summary>
        public static string STR_FIXED_FONT_SIZE_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_FIXED_FONT_SIZE_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string STR_FONT_SIZE_LABEL {
            get {
                return ResourceManager.GetString("STR_FONT_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your preferred font size to match your screen resolution..
        /// </summary>
        public static string STR_FONT_SIZE_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_FONT_SIZE_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string STR_GENERAL_Add {
            get {
                return ResourceManager.GetString("STR_GENERAL_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string STR_GENERAL_Remove {
            get {
                return ResourceManager.GetString("STR_GENERAL_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string STR_GENERAL_SETTINGS_Caption {
            get {
                return ResourceManager.GetString("STR_GENERAL_SETTINGS_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string STR_help_label {
            get {
                return ResourceManager.GetString("STR_help_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        public static string STR_HINT {
            get {
                return ResourceManager.GetString("STR_HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string STR_home_label {
            get {
                return ResourceManager.GetString("STR_home_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon size.
        /// </summary>
        public static string STR_ICON_SIZE_LABEL {
            get {
                return ResourceManager.GetString("STR_ICON_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your preferred icon size to match your screen resolution..
        /// </summary>
        public static string STR_ICON_SIZE_LABEL_TT {
            get {
                return ResourceManager.GetString("STR_ICON_SIZE_LABEL_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string STR_LIGHT_THEME {
            get {
                return ResourceManager.GetString("STR_LIGHT_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload files when application re-starts.
        /// </summary>
        public static string STR_ReloadFilesOnStartUp_CAPTION {
            get {
                return ResourceManager.GetString("STR_ReloadFilesOnStartUp_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string STR_settings_label {
            get {
                return ResourceManager.GetString("STR_settings_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software.
        /// </summary>
        public static string STR_software_label {
            get {
                return ResourceManager.GetString("STR_software_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string STR_UnexpectedError_Caption {
            get {
                return ResourceManager.GetString("STR_UnexpectedError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string STR_Welcome_label {
            get {
                return ResourceManager.GetString("STR_Welcome_label", resourceCulture);
            }
        }
    }
}
